apiVersion: v1
kind: Service
metadata:
  labels:
    app: argo-learn
  name: argo-learn
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30001
  selector:
    app: argo-learn
  type: NodePort
