apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argo-learn
  name: argo-learn
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argo-learn
  template:
    metadata:
      labels:
        app: argo-learn
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
